/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatbot;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.WindowType;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

/**
 *
 * @author CAMILO
 */
public class NewJFrame extends javax.swing.JFrame {

    WebDriver driver; //Ceclaramos en webdriver que controlara chrome
    
    String[] contactos = new String[1000]; //Lista e contactos que manejamos
    
    int cantTabs = 0; //numero de contactos que estaremos manejando
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la URL de DialogFlow");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Activar WhatsApp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Activar ChatBot");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //Obtenemos la ubicacion de nuestro programa
            String localPath=new File(".").getCanonicalPath();
            //Leemos el chromedriver que esta en la misma direccion del programa
            System.setProperty("webdriver.chrome.driver", localPath+"\\chromedriver.exe");
            //Inicializamos ls opciones de chrome
            ChromeOptions optionsGoo = new ChromeOptions();
            //Permitimos la propiedad no-sandbox para evitar problemas en linux
            optionsGoo.addArguments("--no-sandbox");
            //Deshabilitamos las notificaciones
            optionsGoo.addArguments("--disable-notifications");
            //Guardamos la sesion en la carpeta chromeWA
            optionsGoo.addArguments("--user-data-dir="+localPath+"\\chromeWA");
            //Instanciamos un nuevo chromedriver
            driver = new ChromeDriver(optionsGoo);
            //Abrimos whatsapp
            driver.get("https://web.whatsapp.com");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     public void pausa(long sleeptime) {
        try {
            Thread.sleep(sleeptime);
        } catch (InterruptedException ex) {
        }
    }
    
    public void revisaWA() {
        //Variable que almacena la tab de chrome que nos posicionaremos
        int tabSeleccionada=0;
        //Si hay un mensaje
        if(driver.findElements(By.className("aumms1qt")).size()>0){
            //Buscamos el nombre del contacto
            String nombreContacto=driver.findElement(By.className("aumms1qt")).findElement(By.xpath("./../../../../..")).findElement(By.className("zoWT4")).getText();
            //Obtenemos la cantidad mensajes enviados
            int cantNuevosMensajes=Integer.parseInt(driver.findElement(By.className("aumms1qt")).getText());            
            //Damos click en el contacto para abrir el chat
            driver.findElement(By.className("aumms1qt")).click();
            //Obtenemos todos los mensajes
            List<WebElement> webElementsMsgWA = driver.findElements(By.className("_22Msk"));
            //Variable que almacenara los ultimos mensaje enviados
            String mensajeEnviar="";
            //Ciclo que unira todos los ultimos mensajes
            for (int i=cantNuevosMensajes;i>=1;i--){
                //Obtenemos cada mensaje
                String ultimoMensaje = webElementsMsgWA.get(webElementsMsgWA.size()-i).findElement(By.className("i0jNr")).getText();
                //Unimos los mensajes
                mensajeEnviar=mensajeEnviar+" "+ultimoMensaje;
            }
            //Obtenemos todas las TABS
            ArrayList<String> tabs = new ArrayList<String>(driver.getWindowHandles());
            boolean contactoEncontrado=false;
            //Validamos que el nombre de contacto no este en la lista de contactos de lo contrario nos posicionamos en el id del contacto
            for(int tabSel=1;tabSel<=cantTabs;tabSel++){
                //Si el contacto ya existe en la lista
                if(nombreContacto.equals(contactos[tabSel])){
                    //Activamos la bandera y decmos que si encontramos el contacto
                    contactoEncontrado=true;
                    //Abrimos el tab del contacto
                    driver.switchTo().window(tabs.get(tabSel));
                    //Rompemos el ciclo
                    break;
                }
            }
            //Si no se encontro el contacto lo creamos
            if(contactoEncontrado==false){
                //aumentamos el numero de contactos
                cantTabs++;
                //Asignamos el nombre del contacto a la lista de contactos
                contactos[cantTabs]=nombreContacto;
                //Abrimos una nueva pestaña
                driver.switchTo().newWindow(WindowType.TAB);
                //Vamos a la url de nuestro dialogFlow
                driver.get(jTextField1.getText());
            }
            pausa(1000);
            //escribimos el mensaje
            driver.findElement(By.id("query")).sendKeys(mensajeEnviar);
            //Enviamos el mensaje haciendo enter
            driver.findElement(By.id("query")).sendKeys(Keys.ENTER);
            //Esperamos 1 segundo en lo que responde
            pausa(1000);
            //Obtenemos todas las respuestas
            List<WebElement> webElementsMsgDF = driver.findElements(By.className("server-response"));
            //Sacamos la ultima respuesta
            String RespuestaDF = webElementsMsgDF.get(webElementsMsgDF.size()-1).getText();
            //Regresamos a la pestaña de WA
            driver.switchTo().window(tabs.get(0));
            //Escribimos el mensaje
            driver.findElement(By.xpath("//*[@id=\"main\"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]/p")).sendKeys(RespuestaDF);
            //Esperamos 1 segundo
            pausa(1000);
            //Precionamos enter
            driver.findElement(By.xpath("//*[@id=\"main\"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]/p")).sendKeys(Keys.ENTER);
            pausa(1000);
            //Refrescamos el WA web para esperar nuevas preguntas
            driver.get("https://web.whatsapp.com");
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
